services:
  - type: web
    name: minidmart
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: com.mysql.cj.jdbc.Driver
